apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    app: httpd
  namespace: proxy
spec:
  containers:
  - name: httpd
    image: httpd:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    
