apiVersion: v1
kind: Pod
metadata:
  name: app2
  namespace: app
  labels:
    app: app2
spec:
  containers:
  - name: app2
    image: httpd:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    