apiVersion: v1
kind: Pod
metadata:
  name: app3
  labels:
    app: app3
  namespace: app
spec:
  containers:
  - name: app3
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    